"""Reproduce two original quiet PCM chimes; no playback or third-party recordings."""
import argparse
import hashlib
import json
import math
from pathlib import Path
import struct
import wave

RATE = 48_000
CUES = {
    'greeting': (0.44, [(659.255, 0.0, 0.35), (987.767, 0.11, 0.29)]),
    'play': (0.62, [(783.991, 0.0, 0.35), (987.767, 0.10, 0.38), (1174.659, 0.23, 0.37)]),
}


def create(directory):
    directory.mkdir(parents=True, exist_ok=True)
    inventory = []
    for name, (duration, notes) in CUES.items():
        values = []
        for index in range(round(duration * RATE)):
            time = index / RATE
            value = 0.0
            for frequency, start, length in notes:
                t = time - start
                if not 0 <= t < length:
                    continue
                attack = 1 - math.exp(-t / 0.008)
                release = min(1.0, (length - t) / 0.035)
                envelope = attack * math.exp(-t / 0.10) * release
                value += envelope * (math.sin(2 * math.pi * frequency * t) + 0.12 * math.sin(2 * math.pi * frequency * 2.01 * t))
            values.append(value)
        peak = max(abs(v) for v in values)
        samples = [round(v / peak * 0.10 * 32767) for v in values]
        samples[0] = samples[-1] = 0
        pcm = b''.join(struct.pack('<h', sample) for sample in samples)
        path = directory / (name + '.wav')
        with wave.open(str(path), 'wb') as output:
            output.setnchannels(1)
            output.setsampwidth(2)
            output.setframerate(RATE)
            output.writeframes(pcm)
        inventory.append({'file': path.name, 'sampleRate': RATE, 'channels': 1, 'bitsPerSample': 16,
                          'frames': len(samples), 'durationSeconds': duration, 'maximumAbsoluteSample': max(abs(v) for v in samples),
                          'sha256': hashlib.sha256(path.read_bytes()).hexdigest()})
    return inventory


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--output', type=Path, default=Path(__file__).resolve().parents[2] / 'Sources/Spriglet/Resources/PetSounds')
    args = parser.parse_args()
    print(json.dumps({'kind': 'original-spriglet-chimes', 'method': 'Deterministic sine partials and finite attack/decay envelopes, generated by this script. No external recordings.', 'assets': create(args.output)}, indent=2))
