// Generated by tools/SharedContent/sync.py. Edit Configuration/Shared instead.
import Foundation

enum AppText {
    static let appName = "Spriglet"
    static let supportTitle = "Help & Support"
    static let privacyTitle = "Privacy Policy"
    static let licenseTitle = "License"
    static let companionName = "Mallow"
    static let interactionHelp = "Hover to get a reaction. Click to invite. Drag to play. Click elsewhere to return home."
    static let restingPresence = "Curious peek"
    static let engagedPresence = "Invited out"
    static let playingPresence = "Playing"
    static let quitApp = "Quit Spriglet"
    static let showMallow = "Show Mallow"
    static let hideMallow = "Hide Mallow"
    static let pauseMallow = "Pause Mallow"
    static let resumeMallow = "Resume Mallow"
    static let bringHome = "Bring Home"
    static let settings = "Settings…"
    static let animateMallow = "Animate Mallow"
    static let menuBarLabel = "Spriglet controls"
    static let settingsHelp = "These controls apply for this session. Paused Mallow stays still and lets clicks pass through. Show and Bring Home preserve your pause choice."
    static let menuControlsHelp = "Use the leaf in the menu bar to show or hide Mallow, pause or resume animation, bring it home, open Settings or Help, and quit Spriglet."
    static let recoveryHelp = "Hidden Mallow stays hidden through sleep, lock and display changes. Choose Show Mallow or Bring Home, or reopen Spriglet from Finder to recover it. Bring Home and Finder recovery return it to its resting home and preserve Pause."
    static let localHelp = "Everything stays on your Mac. Settings and Help keep keyboard focus in your current app. For support, email support@meetspriglet.com."
    static let settingsTitle = "Settings"
}
