// Generated by tools/SharedContent/sync.py. Edit Configuration/Shared instead.
import Foundation

enum AppText {
    static let appName = "Spriglet"
    static let supportTitle = "Help & Support"
    static let privacyTitle = "Privacy Policy"
    static let licenseTitle = "License"
    static let companionName = "Mallow"
    static let interactionHelp = "Hover to get a reaction. Click to invite. Drag to play. Click elsewhere to return home."
    static let restingPresence = "Curious peek"
    static let engagedPresence = "Invited out"
    static let playingPresence = "Playing"
    static let quitApp = "Quit Spriglet"
    static let launchAtLogin = "Launch at Login"
    static let loginNotRegistered = "Off · Not registered with macOS"
    static let loginEnabled = "On · Registered with macOS"
    static let loginRequiresApproval = "Off · Approval required in System Settings"
    static let loginNotFound = "Unavailable · macOS could not find this app"
    static let loginUnknown = "Unavailable · Unknown macOS registration state"
    static let loginEnableFailed = "Couldn’t enable launch at login"
    static let loginDisableFailed = "Couldn’t disable launch at login"
    static let loginLastAttempt = "Last attempt:"
    static let loginApprovalHelp = "Allow Spriglet in System Settings > General > Login Items & Extensions. It will not launch at login until macOS reports it as enabled. To cancel registration, turn off Launch at Login in Mallow’s menu."
    static let openLoginItemsSettings = "Open Login Items Settings…"
    static let dismissLoginFeedback = "OK"
}
