#!/usr/bin/env python3
"""Generate shared app, App Store, and website content from one set of sources."""

import argparse
import html
import importlib.util
import json
from pathlib import Path
import re
import sys
from urllib.parse import urlsplit

ROOT = Path(__file__).resolve().parents[2]
spec = importlib.util.spec_from_file_location("website_renderer", ROOT / "tools/AppStore/website/build.py")
website = importlib.util.module_from_spec(spec)
spec.loader.exec_module(website)
TOKEN = re.compile(r"\{\{([A-Za-z][A-Za-z0-9]*)\}\}")


def expand(value, context):
    if isinstance(value, dict): return {key: expand(item, context) for key, item in value.items()}
    if isinstance(value, list): return [expand(item, context) for item in value]
    if not isinstance(value, str): return value
    def replace(match):
        key = match[1]
        if key not in context: raise ValueError(f"Unknown shared content token: {key}")
        return str(context[key])
    result = TOKEN.sub(replace, value)
    if "{{" in result or "}}" in result: raise ValueError("Unresolved shared content token")
    return result


def read_context(root):
    source = root / "Configuration/Shared"
    brand = json.loads((source / "brand.json").read_text())
    for key in ("appName", "publisher", "websiteURL", "supportEmail"):
        value = brand.get(key)
        if not isinstance(value, str) or not value.strip() or value != value.strip() or any(ord(c) < 32 for c in value):
            raise ValueError(f"Invalid brand field: {key}")
    origin = urlsplit(brand["websiteURL"])
    if origin.scheme != "https" or not origin.hostname or origin.netloc != origin.hostname or origin.path or origin.query or origin.fragment:
        raise ValueError("websiteURL must be an HTTPS origin without a path or credentials")
    if not re.fullmatch(r"[A-Za-z0-9._%+-]+@" + re.escape(origin.hostname), brand["supportEmail"]):
        raise ValueError("Support email must use the website domain")
    if not isinstance(brand.get("copyrightYear"), int) or not 2000 <= brand["copyrightYear"] <= 9999:
        raise ValueError("Invalid copyright year")
    context = {**brand, "websiteDomain": origin.hostname, "supportURL": brand["websiteURL"] + "/support",
               "privacyPolicyURL": brand["websiteURL"] + "/privacy",
               "copyright": f'{brand["copyrightYear"]} {brand["publisher"]}'}
    labels = expand(json.loads((source / "en-US.json").read_text()), context)
    for key, value in labels.items():
        if not re.fullmatch(r"[a-z][A-Za-z0-9]*", key) or not isinstance(value, str) or not value or any(ord(c) < 32 for c in value):
            raise ValueError(f"Invalid shared UI text: {key}")
    return {**context, **labels}, labels


def output_files(root=ROOT):
    source = root / "Configuration/Shared"
    context, labels = read_context(root)
    documents = {name: expand((source / f"{name}.md").read_text(), context) for name in ("privacy", "support", "product")}
    metadata = expand(json.loads((source / "app-store.en-US.json").read_text()), context)
    outputs = {
        "PRIVACY.md": documents["privacy"],
        "tools/AppStore/support-page.md": documents["support"],
        "tools/AppStore/product-page.md": documents["product"],
        "tools/AppStore/metadata/en-US.json": json.dumps(metadata, indent=2, ensure_ascii=False) + "\n",
        "Sources/Spriglet/Resources/PrivacyPolicy.md": documents["privacy"],
        "Sources/Spriglet/Resources/Support.md": documents["support"],
        "Sources/Spriglet/Resources/License.txt": (root / "LICENSE").read_text(),
        "Configuration/Info.plist": expand((source / "Info.plist").read_text(), {key: html.escape(str(value)) for key, value in context.items()}),
    }
    # JSON string escaping is also valid for these validated, single-line Swift literals.
    literal = lambda value: json.dumps(value, ensure_ascii=False)
    swift = "// Generated by tools/SharedContent/sync.py. Edit Configuration/Shared instead.\nimport Foundation\n\nenum AppText {\n"
    swift += f'    static let appName = {literal(context["appName"])}\n'
    swift += "".join(f"    static let {key} = {literal(value)}\n" for key, value in labels.items())
    swift += "}\n\nenum AppLinks {\n"
    for key, value in (("privacy", context["privacyPolicyURL"]), ("support", context["supportURL"]), ("email", "mailto:" + context["supportEmail"])):
        swift += f"    static let {key} = URL(string: {literal(value)})!\n"
    swift += '''
    static var versionDescription: String {
        let info = Bundle.main.infoDictionary ?? [:]
        let version = info["CFBundleShortVersionString"] as? String ?? "Unknown"
        let build = info["CFBundleVersion"] as? String ?? "Unknown"
        return "\\(version) (\\(build))"
    }
}
'''
    outputs["Sources/Spriglet/App/SharedContent.generated.swift"] = swift
    outputs.update({"tools/AppStore/website/public/" + name: text for name, text in website.outputs(context, documents).items()})
    icon_root = root / "Sources/Spriglet/Assets.xcassets/AppIcon.appiconset"
    images = json.loads((icon_root / "Contents.json").read_text())["images"]
    # Follow the asset catalog's filename, not a separate website logo or assumed file name.
    icon = next(item for item in images if item["idiom"] == "mac" and item["size"] == "128x128" and item["scale"] == "1x")
    icon_path = (icon_root / icon["filename"]).resolve()
    if icon_path.parent != icon_root.resolve(): raise ValueError("Icon must be inside the app icon catalog")
    outputs["tools/AppStore/website/public/spriglet.png"] = icon_path.read_bytes()
    config = {"name": "meetspriglet-support", "compatibility_date": "2026-09-15", "send_metrics": False,
              "workers_dev": False, "routes": [{"pattern": context["websiteDomain"], "custom_domain": True}],
              "build": {"command": 'PYTHONDONTWRITEBYTECODE=1 python3 "$(git rev-parse --show-toplevel)/tools/SharedContent/sync.py"',
                        "watch_dir": ["../../../Configuration/Shared", "../../../Sources/Spriglet/Assets.xcassets/AppIcon.appiconset", "../../../LICENSE", "../../SharedContent/sync.py", "./build.py"]},
              "assets": {"directory": "./public", "html_handling": "auto-trailing-slash", "not_found_handling": "404-page"},
              "observability": {"enabled": False}}
    outputs["tools/AppStore/website/wrangler.jsonc"] = "// Generated from Configuration/Shared/brand.json by tools/SharedContent/sync.py.\n" + json.dumps(config, indent=2) + "\n"
    return {name: value.encode() if isinstance(value, str) else value for name, value in outputs.items()}


def synchronize(root=ROOT, check=False):
    outputs = output_files(root)
    stale = [name for name, content in outputs.items() if not (root / name).is_file() or (root / name).read_bytes() != content]
    if check and stale:
        raise ValueError("Stale shared content; run python3 tools/SharedContent/sync.py:\n" + "\n".join(stale))
    if not check:
        for name in stale:
            target = root / name
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_bytes(outputs[name])
    return stale


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Reject stale generated files without changing them")
    parser.add_argument("--source-root", type=Path, default=ROOT)
    args = parser.parse_args()
    try:
        changed = synchronize(args.source_root, args.check)
        print(f"Shared app, store, and website content is synchronized ({len(changed)} updated files).")
    except (OSError, ValueError, KeyError, StopIteration) as error:
        print(str(error), file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__": sys.exit(main())
