from html.parser import HTMLParser
import importlib.util
from pathlib import Path
import unittest

ROOT = Path(__file__).resolve().parents[3]
spec = importlib.util.spec_from_file_location('shared_sync', ROOT / 'tools/SharedContent/sync.py')
sync = importlib.util.module_from_spec(spec)
spec.loader.exec_module(sync)


class Elements(HTMLParser):
    def __init__(self, source):
        super().__init__()
        self.ids = set()
        self.anchors = []
        self.feed(source)

    def handle_starttag(self, tag, attributes):
        values = dict(attributes)
        if 'id' in values:
            if values['id'] in self.ids:
                raise ValueError('Duplicate element ID: ' + values['id'])
            self.ids.add(values['id'])
        if tag in ('a', 'use'):
            self.anchors.append(values.get('href', ''))


class HomepageTests(unittest.TestCase):
    def setUp(self):
        self.context, _ = sync.read_context(ROOT)
        import json
        self.presentation = sync.expand(json.loads((ROOT / 'Configuration/Shared/website.en-US.json').read_text()), self.context)

    def render(self):
        return sync.website.homepage(self.context, self.presentation, '/spriglet.png?v=fixture')

    def test_anchor_destinations_and_vector_references_exist(self):
        parsed = Elements(self.render())
        for link in parsed.anchors:
            if link.startswith('#'):
                self.assertIn(link[1:], parsed.ids)

    def test_pending_store_uses_real_preview_and_its_limitations(self):
        page = self.render()
        self.assertIn(self.presentation['home']['previewURL'], page)
        self.assertIn('not notarized', page)
        self.assertNotIn('Available on the Mac App Store.', page)
        self.assertNotIn('href="https://apps.apple.com', page)

    def test_verified_store_configuration_replaces_preview_copy_and_link(self):
        # Fixture only: never written into the checked-in website.
        self.presentation['home']['storeURL'] = 'https://apps.apple.com/us/app/spriglet/id1234567890'
        page = self.render()
        self.assertIn('Get on the Mac App Store', page)
        self.assertIn('Available on the Mac App Store.', page)
        self.assertNotIn(self.presentation['home']['previewURL'], page)
        self.assertNotIn('not notarized', page)
        self.assertIn('href="https://meetspriglet.com/support">Installation help', page)

    def test_unsafe_store_and_source_destinations_are_rejected(self):
        for url in ('javascript:alert(1)', 'https://apps.apple.com.evil.invalid/app/id123', 'https://user@apps.apple.com/app/id123', 'https://apps.apple.com/app/not-a-product'):
            with self.subTest(url=url), self.assertRaises(ValueError):
                self.presentation['home']['storeURL'] = url
                self.render()
        self.presentation['home']['storeURL'] = None
        for key in ('sourceURL', 'previewURL'):
            original = self.presentation['home'][key]
            for url in ('https://github.com/eyenpi/spriglet-evil', '//github.com/eyenpi/spriglet', 'https://github.com.evil.invalid/eyenpi/spriglet'):
                with self.subTest(key=key, url=url), self.assertRaises(ValueError):
                    self.presentation['home'][key] = url
                    self.render()
            self.presentation['home'][key] = original

    def test_home_copy_is_escaped_and_no_template_tokens_remain(self):
        self.presentation['home']['heroBody'] = '<script>alert("hello")</script>'
        page = self.render()
        self.assertIn('&lt;script&gt;', page)
        self.assertNotIn('<script>alert', page)
        self.assertNotIn('{{', page)

    def test_only_homepage_local_deferred_script_is_allowed(self):
        for markup, home in (('<script src="/home.js" defer></script>', False), ('<script src="https://external.invalid/tracker.js" defer></script>', True), ('<script src="/home.js"></script>', True), ('<a onclick="alert(1)">Click</a>', True)):
            with self.subTest(markup=markup), self.assertRaises(ValueError):
                sync.website.LinkCheck(homepage=home).feed(markup)
        sync.website.LinkCheck(homepage=True).feed('<script src="/home.js" defer></script>')

    def test_website_changes_preserve_bundled_app_and_policy_bytes(self):
        before = sync.output_files()
        # Homepage additions must not change the existing app's generated bytes.
        for path in ('Sources/Spriglet/Resources/Support.md', 'Sources/Spriglet/Resources/PrivacyPolicy.md',
                     'Sources/Spriglet/App/SharedContent.generated.swift', 'Configuration/Info.plist',
                     'tools/AppStore/metadata/en-US.json', 'PRIVACY.md'):
            self.assertEqual(before[path], (ROOT / path).read_bytes())


if __name__ == '__main__':
    unittest.main()
